export const cats = [
    {
        id: 12,
        description: "Elegante y travieso, parece que siempre lleva puesto un esmoquin.",
        imageUrl: "http://localhost:3001/img/tuxedo.jpg",
        colorPrimario: "black",
        colorSecundario: "white",
        breed: "Tuxedo",
    },
    {
        id: 1,
        description: "La combinación clásica del calico: tres colores que lo hacen único e inconfundible.",
        imageUrl: "http://localhost:3001/img/Calico.jpg",
        colorPrimario: "white",
        colorSecundario: "black",
        colorTerciario: "orange",
        breed: "Calico",
    },
    {
        id: 2,
        description: "Un gato elegante de color café con una mirada profunda y mística.",
        imageUrl: "http://localhost:3001/img/GatoCafe.jpg",
        colorPrimario: "brown",
        colorSecundario: "brown",
        breed: "Marrón",
    },
    {
        id: 4,
        description: "Una mezcla suave de crema con manchas oscuras que realzan su belleza.",
        imageUrl: "http://localhost:3001/img/GatoCremaN.jpg",
        colorPrimario: "cream",
        colorSecundario: "black",
        breed: "Crema y Negro",
    },
    {
        id: 5,
        description: "Un felino vibrante con un patrón naranja y blanco muy amigable.",
        imageUrl: "http://localhost:3001/img/GatoNaraB.jpg",
        colorPrimario: "orange",
        colorSecundario: "white",
        breed: "Naranja y Blanco",
    },
    {
        id: 6,
        description: "Completamente negro, elegante y sigiloso como una pequeña pantera.",
        imageUrl: "http://localhost:3001/img/NN.jpg",
        colorPrimario: "black",
        colorSecundario: "black",
        breed: "Negro",
    },
    {
        id: 7,
        description: "Un gato naranja brillante, lleno de energía y alegría.",
        imageUrl: "http://localhost:3001/img/NaraNara.jpg",
        colorPrimario: "orange",
        colorSecundario: "orange",
        breed: "Naranja",
    },
    {
        id: 8,
        description: "Blancura pura y radiante, un gato que parece una pequeña nube.",
        imageUrl: "http://localhost:3001/img/gatBB.jpg",
        colorPrimario: "white",
        colorSecundario: "white",
        breed: "Blanco",
    },
    {
        id: 9,
        description: "Contrasis de blanco y negro en un patrón moteado y único.",
        imageUrl: "http://localhost:3001/img/gatoBN.jpg",
        colorPrimario: "white",
        colorSecundario: "black",
        breed: "Moteado Blanco y Negro",
    },
    {
        id: 10,
        description: "Gris suave con toques blancos que le dan un aire distinguido.",
        imageUrl: "http://localhost:3001/img/gatoGB.jpg",
        colorPrimario: "gray",
        colorSecundario: "white",
        breed: "Gris y Blanco",
    },
    {
        id: 11,
        description: "Un gris uniforme y elegante, perfecto para las siestas tranquilas.",
        imageUrl: "http://localhost:3001/img/gatoGG.jpg",
        colorPrimario: "gray",
        colorSecundario: "gray",
        breed: "Gris",
    },
];
